tasks:
  - name: Init
    init: |
      printf "\n[settings]\napi_key = $WAKATIME_API_KEY\n" > ~/.wakatime.cfg
      bundle install
      
vscode:
  extensions:
    - streetsidesoftware.code-spell-checker-french
    - streetsidesoftware.code-spell-checker
    - github.vscode-pull-request-github
    - eamodio.gitlens