tasks:
  - name: Configuring Wakatime
    command: |
      echo "[settings]" >> /home/gitpod/.wakatime.cfg
      echo "api_key = $WAKATIME_API_KEY" >> /home/gitpod/.wakatime.cfg
      exit
      
vscode:
  extensions:
    - streetsidesoftware.code-spell-checker-french
    - streetsidesoftware.code-spell-checker
    - github.vscode-pull-request-github
    - eamodio.gitlens